# Generated by Django 5.1.4 on 2025-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='nbenfant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='nbpersonne',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
