<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_checkout_nbenfant_checkout_nbpersonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pays',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_checkout_nbenfant_checkout_nbpersonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pays',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
>>>>>>> master
