<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_checkout_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(verbose_name=500)),
                ('image', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now=True)),
                
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_checkout_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField(verbose_name=500)),
                ('image', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now=True)),
                
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
>>>>>>> master
