<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_vol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vol',
            options={},
        ),
        migrations.RemoveField(
            model_name='vol',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='image',
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_vol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vol',
            options={},
        ),
        migrations.RemoveField(
            model_name='vol',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='image',
        ),
    ]
>>>>>>> master
