# Generated by Django 5.1.4 on 2025-01-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_vol_options_remove_vol_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='datd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vol',
            name='datf',
            field=models.DateTimeField(),
        ),
    ]
