<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_vol_datd_alter_vol_datf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vol',
            name='datd',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='datf',
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_vol_datd_alter_vol_datf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vol',
            name='datd',
        ),
        migrations.RemoveField(
            model_name='vol',
            name='datf',
        ),
    ]
>>>>>>> master
