# Generated by Django 5.1.4 on 2025-01-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_vol_datd_remove_vol_datf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vol',
            name='price',
        ),
    ]
