# Generated by Django 5.1.4 on 2025-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_hotel_description_checkout_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='price',
        ),
        migrations.AddField(
            model_name='checkout',
            name='select',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
