# Generated by Django 5.1.4 on 2025-01-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0015_remove_checkout_price_checkout_select"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="nbenfant",
            new_name="nbenfant_moin12",
        ),
        migrations.AddField(
            model_name="checkout",
            name="nbenfant_moin6",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
