# Generated by Django 5.1.4 on 2025-01-28 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0016_rename_nbenfant_checkout_nbenfant_moin12_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="nbenfant_moin12",
            new_name="nbenfant",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="nbenfant_moin6",
        ),
    ]
