# Generated by Django 5.1.4 on 2025-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0017_rename_nbenfant_moin12_checkout_nbenfant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="nbbebe",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
