# Generated by Django 5.1.4 on 2025-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_checkout_nbbebe'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
