# Generated by Django 5.1.4 on 2025-01-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_hotel_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='star',
        ),
    ]
