# Generated by Django 5.1.4 on 2025-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_passager_reservation_delete_reserver_vol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserver_vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbpersonne', models.EmailField(max_length=200)),
                ('Compagnie', models.CharField(max_length=200)),
                ('Départ', models.CharField(max_length=200)),
                ('Arrivée', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('Prix', models.IntegerField(blank=True, null=True)),
                ('vol', models.CharField(max_length=500)),
                ('Classe', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Passager',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
