# Generated by Django 4.2.16 on 2025-02-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_reserver_vol_delete_passager_delete_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserver_vol',
            old_name='Arrivée',
            new_name='arrivée',
        ),
        migrations.RenameField(
            model_name='reserver_vol',
            old_name='Classe',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='reserver_vol',
            old_name='Compagnie',
            new_name='compagnie',
        ),
        migrations.RemoveField(
            model_name='reserver_vol',
            name='Départ',
        ),
        migrations.RemoveField(
            model_name='reserver_vol',
            name='Prix',
        ),
        migrations.AddField(
            model_name='reserver_vol',
            name='depart',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserver_vol',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserver_vol',
            name='nbpersonne',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('passeport', models.CharField(max_length=255)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes', to='polls.reserver_vol')),
            ],
        ),
        migrations.AddField(
            model_name='reserver_vol',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
